name: CI

on:
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]
  workflow_dispatch:

jobs:
  metadata:
    name: Read project Id and dataset
    runs-on: ubuntu-latest
    outputs: 
      Deployment: ${{steps.set.outputs.deployment}}
    steps:
      - uses: actions/checkout@v3
      - name: parse itv.yaml
        id: set
        run: |
          echo "Reading config for branch: $GITHUB_REF_NAME"
          BRANCH_REF="$GITHUB_REF"
          
            deployment=$(yq -o=json 'to_entries |map(select (.value.ref == "'$BRANCH_REF'")) |.[0].value' itv.yaml)
          echo "deployment<<EOF" >> $GITHUB_OUTPUT
          echo "$deployment" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        
  deploy:
    needs: metadata
#    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v3
      - name: Authenticate to GCP (Dev)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEV_CREDS }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Create dataset & deploy views and tables to Dev
        run: | 
          DEPLOYMENT_JSON='${{ needs.metadata.outputs.deployment }}'
          PROJECT_ID=$(echo "$DEPLOYMENT_JSON" |jq -r '.project_id')
          DATASET=$(echo "$DEPLOYMENT_JSON" | jq -r '.dataset')
          CREATE_DATASET=$(echo "$DEPLOYMENT_JSON" | jq -r '.create_dataset')
          VIEW_SCOPE=$(echo "$DEPLOYMENT_JSON" | jq -r '.view_scope')
          TABLE_SCOPE=$(echo "$DEPLOYMENT_JSON" | jq -r '.table_scope')
          echo "Using PROJECT_ID=$PROJECT_ID"
          echo "Using DATASET=$DATASET"
          echo "VIEW_SCOPE=$VIEW_SCOPE"
          echo "TABLE_SCOPE=$TABLE_SCOPE"
          # Create dataset if required
          if [[ "$CREATE_DATASET" == "true" ]]; then
          echo "Creating datset... is $CREATE_DATASET "
          bq --location=US mk --dataset --project_id="$PROJECT_ID" "$DATASET" || echo "dataset may already exist"
          else
          echo "Skipping dataset creation"
          fi
          # Process Views
          if [[ -n "$VIEW_SCOPE" ]]; then
          IFS=',' read -r -a VIEWS <<< "$VIEW_SCOPE"
          echo "Deploying views..."
          for file in views/*.sql; do
          base_name=$(basename "$file" .sql)
          if [[ "$VIEW_SCOPE" == "all" || " ${VIEWS[*]} " =~ " $base_name " ]]; then
          echo "Deploying view: $base_name"
          FINAL_SQL=$(cat "$file" | sed "s/{{PROJECT_ID}}/$PROJECT_ID/g" | sed "s/{{DATASET}}/$DATASET/g")
          bq query --use_legacy_sql=false --project_id="$PROJECT_ID" "$FINAL_SQL"
          else
          echo "Skipping view: $base_name"
          fi
          done
          else
          echo "No view_scope defined — skipping view deployment"
          fi
          
           # Process Tables
          if [[ -n "$TABLE_SCOPE" ]]; then
          IFS=',' read -r -a TABLES <<< "$TABLE_SCOPE"
          echo "Deploying tables..."
          for file in tables/*.sql; do
          base_name=$(basename "$file" .sql)
          if [[ "$TABLE_SCOPE" == "all" || " ${TABLES[*]} " =~ " $base_name " ]]; then
          echo "Deploying table: $base_name"
          FINAL_SQL=$(cat "$file" | sed "s/{{PROJECT_ID}}/$PROJECT_ID/g" | sed "s/{{DATASET}}/$DATASET/g")
          bq query --use_legacy_sql=false --project_id="$PROJECT_ID" "$FINAL_SQL"
          else
          echo "Skipping table: $base_name"
          fi
          done
          else
          echo "No table_scope defined — skipping table deployment"
          fi
