# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "dev","main" ]
  pull_request:
    branches: [ "dev","main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    name: Deploy to Dev (fluid-analogy)

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Authenticate to GCP (Dev)
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_DEV_CREDS }}

      # Runs a set of commands using the runners shell
      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Deploy SQL views to Dev
        run: | 
          for file in views/*.sql; do
            echo "Deploying $file to Dev project..."
             bq query --use_legacy_sql=false --project_id=fluid-analogy-459522-a0 "$(cat $file)"
          done
          for file in tables/*.sql; do
            echo "Deploying $file to Dev project..."
             bq query --use_legacy_sql=false --project_id=fluid-analogy-459522-a0 "$(cat $file)"
          done
